### ISSUE TITLE
Launching containers without `-d` hangs

### ISSUE THREAD

**Issue by marcosnils** [franela/docker-machine-driver-pwd#1]
When launching non-detached containers, they'll be left  under "Created" state in PWD and machine will just hang.

**Comment by xetorthio** [comment]
Not sure I understand the connection with launching containers and machine.
Care to elaborate more? A step by step example would be nice.

**Comment by marcosnils** [comment]
try running any container *non-detached* though this driver and machine will hang and container will be left as "Created" in PWD

**Comment by xetorthio** [comment]
Firstly, how do you run a container `through the driver`? AFAIK you can only set the env variables so the docker cli launches the container. But that's all you can do.

I followed your "steps" and effectively the docker cli hangs, but not docker-machine. After docker-cli hangs, you can still list your machines, launch new ones and delete existing ones. So this drivers still works as expected.

Now, trying to do the same thing totally outside of the scope of machine, by exporting `DOCKER_HOST` and running a `non-detached` container, the same thing happens: docker-cli hangs.

So 2 things:

1. This issue doesn't belong to this repo, but probably to PWD repo.
2. Seems like an issue with attaching stdin, stderr and stdout.

**Comment by marcosnils** [comment]
> Firstly, how do you run a container through the driver? AFAIK you can only set the env variables so the docker cli launches the container. But that's all you can do.

Yes, I mean through eval $(docker-machine env test). So it's a PWD / CLI issue as you say.

> This issue doesn't belong to this repo, but probably to PWD repo.

I'll put it there


> Seems like an issue with attaching stdin, stderr and stdout.

yup
