### ISSUE TITLE
Could not create instance <nil> &{409 Conflict 409 HTTP/1.1 1 1

### ISSUE THREAD

**Issue by anthonydahanne** [franela/docker-machine-driver-pwd#11]
Hello,
I've just downloaded the latest release of docker-machine-driver-pwd (v0.0.5) and installed it on my mac : 
```
cp ~/Downloads/docker-machine-driver/darwin/amd64/docker-machine-driver-pwd /usr/local/bin/ 
```
Then, I went to http://play-with-docker.com and I set up my PWD_URL env variable accordingly : 
```
export PWD_URL="http://host4.labs.play-with-docker.com/p/90ea5123-a016-46a5-a766-787b8f83fcf3"
```
and finally I tried to create a docker-machine instance : 
```
$ docker-machine create -d pwd manager1
Running pre-create checks...
Creating machine...
Error creating machine: Error in driver during machine creation: Could not create instance <nil> &{409 Conflict 409 HTTP/1.1 1 1 map[Date:[Wed, 18 Oct 2017 03:17:01 GMT] Content-Length:[0] Content-Type:[text/plain; charset=utf-8]] {} 0 [] false false map[] 0xc420110800 <nil>}
```
I also tried with --pwd-url, but got the exact same failure...

**Comment by marcosnils** [comment]
Hmmm this is weird. Have you tried creating another session?. Just tried it and it works. Maybe that specific session got corrupted somehow

**Comment by anthonydahanne** [comment]
I tried with several, I'll try to show you today

**Comment by marcosnils** [comment]
Sure, please come by if you see me around.

**Comment by anthonydahanne** [comment]
thanks for your help, I forgot that docker machine is only to create, not connect to existing instances

**Comment by brauliogr** [comment]
Can you solve this problem?
