### ISSUE TITLE
uname says x86_64, had to use 386 driver

### ISSUE THREAD

**Issue by mjbright** [franela/docker-machine-driver-pwd#2]
uname -a gives

> Linux node1 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 Linux

But I couldn't use the x86_64 driver, it complained
> Error starting plugin binary: fork/exec /usr/local/bin/docker-machine-driver-pwd: no such file or directory

So I tried copying
    linux/386/docker-machine-driver-pwd to /usr/local/bin

and now docker-machine create worked (well it got farther, it created a machine)

**Comment by marcosnils** [comment]
@mjbright what does `file /usr/local/bin/docker-machine-driver-pwd` return for the x86_64 file?

In any case, I've just tried to download it from the releases section and it works fine in my environment

**Comment by mjbright** [comment]
This was on http://play-with-docker.com/, there is no file command in the
alpine image.

**Comment by marcosnils** [comment]
Oh, you're using the machine driver inside PWD?. That's interesting, let me try it

**Comment by marcosnils** [comment]
@jpetazzo I know that you like tinkering with these stuff, maybe you'd like to take a look also?

**Comment by marcosnils** [comment]
@mjbright found the reason. the 386 binary is statically linked vs the x86_64 file, that's why it works. I'm not sure why go decided to statically compile that one but not the 64 bit version one. I'll fix this with a new release.

**Comment by jpetazzo** [comment]
Nice catch!

**Comment by marcosnils** [comment]
Fixed. Also found why it happened:

https://github.com/mitchellh/gox/issues/55
