### ISSUE TITLE
Created docker-machine but fails with 'Could not create instance <nil> '

### ISSUE THREAD

**Issue by mjbright** [franela/docker-machine-driver-pwd#3]
In a session on http://play-with-docker.com/:

I set PWD_SESSION_ID
```
$ export PWD_SESSION_ID=play
```

Then created a docker-machine (using 386 driver, see issue #1 ).

```
$ docker-machine create -d pwd node1
Running pre-create checks...
Creating machine...
Error creating machine: Error in driver during machine creation: Could not create instance <nil> &{500 Internal Server Error 500 HTTP/1.1 1 1 map[Date:[Mon,
 09 Jan 2017 17:03:52 GMT] Content-Type:[text/plain; charset=utf-8]] 0x1898a090 -1 [chunked] false map[] 0x188debd0 <nil>}
The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
```

Subsequent ```docker-machine ls``` shows machine was created but not completely ...
```
$ docker-machine ls
NAME    ACTIVE   DRIVER   STATE     URL   SWARM   DOCKER    ERRORS
node1   *        pwd      Running                 Unknown
```

**Comment by marcosnils** [comment]
@mjbright you're using the v0.0.2 release, right?

**Comment by marcosnils** [comment]
@mjbright the SESSION_ID should be the number you get `after` creating a session id PWD. You can't set whatever you want in that value. Check the README instructions

**Comment by mjbright** [comment]
OK, I didn't understand that from the README.

Trying again using the play-with-docker created session-id produced the
same error.

**Comment by mjbright** [comment]
Yes, 0.0.2 release.

**Comment by mjbright** [comment]
Here's my instance (for 2 more hours ...)

http://play-with-docker.com/p/dc75aca5-3b20-46b2-98a0-973d00ef8797#dc75aca5_node1

**Comment by marcosnils** [comment]
> Here's my instance (for 2 more hours ...)

@mjbright just tried and it works. You incorrectly set the PWD_SESSION_ID variable. In this case the session id would be `dc75aca5-3b20-46b2-98a0-973d00ef8797`. I left it configured in that session so you an play around with it.

**Comment by mjbright** [comment]
duh ... thanks ... I see you picked up the full session id from the browser
url.
OK.

And thanks a bunch for such a useful tool !

**Comment by marcosnils** [comment]
> And thanks a bunch for such a useful tool !

thanks to you for taking the time to use it and report issues. I'll investigate the binary thing later today.
